### PR TITLE
Rita 2020 04 08 redcap checklist project review

### PR DESCRIPTION
**Pull request by lijenn**
- added more specifications and detail for location of buttons and next steps
- reorganized flow for each section
- will add in location of REDCap map when uploaded onto GH

### CODE REVIEW

**Comment by staceypark** [comment]
@lijenn @ritahitching I'm confused as to why this looks like a pull request for Rita's branch but the request is from Jenn?

**Comment by lijenn** [comment]
@staceypark @ritahitching I had bandwidth to pick up this task and since Rita was out sick at the time, it made sense to hand it off to me as I had worked on this previously. I worked off of her branch since there was feedback made towards her edits.

**Comment by lzim** [comment]
Great thanks @lijenn for keeping this moving!

Cross-ref note: @ritahitching @branscombj @dlkibbe - This is a great example of something that needs the #1364 **Standard Header** rules defined for all the comments in the **Team PSD Manual.**

- As we discussed at **All Hands** Tuesday, we have open 23 **documents_teams** cards in the **document_tracker** and we have a draft TOC of documents like this already created on #1192 **Team PSD Manual.**

- Unfortunately, all the documents use formatting in their own ways.
- It makes it hard to use them like a manual.
- Before we create 23 more items that also use formatting in their own ways..._let’s standardize to avoid rework_ 😅 !

**Comment by staceypark** [comment]
@lijenn Some additional comments to the ones Lindsey made above:
1. I remember this checklist was initially made specific to a project, and there seems to still be legacies of that:
- For example, not every project will have branching logic. You should frame the check for branching logic so people will know that. Perhaps the checklist needs to address all the possible section that could need checking or fixing and how to do that. But frame at the top that not all of these may apply
> Be sure to check the **branching logic** within each measure/variable in the instrument.
>   - Click on the **green icon with forked arrows** located above the title of the measure/variable. 

2. I don't see the VA RedCap site linked or indicated anywhere. I wouldn't be able to follow this checklist since I wouldn't know where to go! 🤣

**Pull request closed without merging**
