### PR TITLE
Feature gh pages manual update

### PR DESCRIPTION
**Pull request by ljmoody**
FYI: if needed, use [**Lucidchart #2999_team_psd_safe_workflows**](https://lucid.app/lucidchart/0cd93668-a02d-4176-b97d-4f342985a57f/edit?invitationId=inv_3462b1a9-3207-4813-87e1-993924811a3f&page=0_0#) as reference
### Please QA files with content edits, which include:
- [x] 3.0_standard_operations.md
- [x] 4.0_shared_workstreams.md
- [x] 4.1_manage_teampsd_vha_worflows_via_teams_and_outlook.md
- [x] 4.2_edit_guide_plan_qa_sync.md
- [x] 4.4_manage_outlook_shared_calendars_and_meeting_series.md
- [x] 4.5_improve_mtl_repo_pr_qa.md
- [x] 4.6_scope_workflow_dependencies_using_user_stories_and_zenhub_github.md
- [x] 4.8_onboard_new_team_member_to_va.md
- [x] 4.9_hire_a_new_team_member_through_pavir.md
- [x] 4.10_create_edit_github_issue_template.md
- [x] 4.11_export_lists_mtl_data_research_analysis.md
- [x] 4.12_configure_mtlhelp_mtlinfo_email_settings.md
- [x] 4.13_teampsd_onboarding_cadence_cycles.md
- [x] 4.14_develop_personal_professional_goals_meaningful_teampsd_progress.md
- [x] 4.15_roadmap_user_stories.md
- [x] 4.16_update_teampsd_website.md
- [x] 4.17_offboarding_teampsd_member.md
- [x] 5.0_co_coordinated_workstreams_r_and_d_dataops_devops.md
- [x] 5.1_manage_research_repository_including_readme.md
- [x] 5.2_report_progress_for_r21_r01_iir_grants.md
- [x] 5.3_contribute_to_teampsd_manuscript.md
- [x] 5.4_request_new_research_data.md
- [x] 5.5_submitting_requisition.md
- [x] 5.6_submit_vaco_and_vapahcs_progress_report.md
- [x] 6.0_research_and_development_workstreams.md
- [x] 6.1_manage_research_and_development_workstream_permissions.md
- [x] 6.3_manage_research_calendar_and_mtl_info_inbox.md
- [x] 6.6_produce_patient_and_provider_enrollment_tables_for_progress_reports.md
- [x] 6.7_renew_or_modify_irb_w_stanford_eprotocol.md
- [x] 6.10_manage_authorship_app.md
- [x] 6.14_manage_search_engines_for_websites
- [x] 6.15_use_irbnet_rdis_manage_active_irb_approved_research_projects.md
- [x] 7.0_dataops_workstreams.md
- [x] 7.1_manage_dataops_workstream_permissions.md
- [x] 7.4_sync_bug_tracker_progress_to_squash_teampsd_and_research_bugs.md
- [x] 7.5_sync_feature_tracker_progress_to_develop_teampsd_and_research_features.md
- [x] 7.7_update_r_notebook.md
- [x] 7.8_improve_msd365_integration.md
- [x] 7.9_refresh_data_r01_or_iir.md
- [x] 7.12_update_powerbi_data_ui_instances.md
- [x] 7.13_report_data_ui_power_ui_use_data.md
- [x] 7.14_update_power_bi_data_report_test_through_deployment_pipeline.md
- [x] 7.15_schedule_daily_data_ui_refresh.md
- [x] 7.16_create_test_release_branch.md
- [x] 8.0_peopleops_workstreams.md
- [x] 8.1_manage_peopleops_workstream_permissions.md
- [x] 8.3_manage_operations_calendar_and_inbox.md
- [x] 8.4_setup_send_r01_iir_aim2_provider_surveys_va_redcap.md
- [x] 8.5_engage_new_mtl_coplanning_group.md
- [x] 8.6_setup_new_mtl_live_team_without_research_eval.md
- [x] 8.7_setup_new_mtl_live_team_with_research_eval.md
- [x] 8.8_facilitate_mtl_live_team_w_research_eval_crm.md
- [x] 8.9_setup_new_coplanning_group_team_from_site_varedcap_for_fidelity_ratings.md
- [x] 8.10_purchase_through_reqlogic.md
- [x] 8.11_coordinate_ilead_workflow.md
- [x] 9.0_co_coordinated_workstreams_dataops_peopleops.md
- [x] 9.1_test_new_mtl_release.md
- [x] 9.2_cicd_for_system_dynamics_model_files.md
- [x] 9.3_upload_data_to_sim_ui.md
- [x] 9.4_teampsd_monthly_process_screencast.md
- [x] 9.5_teampsd_monthly_process_youtube.md
- [x] 9.6_week_4.md
- [x] 11.0_ms_teams.md
- [x] 12.0_open_science_framework.md
- [x] 13.0_lucidcharts.md
- [x] 16.0_track_issues_bugs_and_features.md
### In addition, these files were also modified:
- [x] cspelldict.txt
- [x] readme file
- [x] bookdown.yml

### CODE REVIEW

**Comment by lijenn** [comment]
DECISION from wk4 aug_epic training_workflow w/ Laura and Lindsey: @lijenn will do a birds eye review and pull into Master.

**Comment by lijenn** [comment]
Amazing job on all this hard work, Laura! I'm merging shortly :)

**Comment by ljmoody** [comment]
> Amazing job on all this hard work, Laura! I'm merging shortly :)

Thanks for your kind words! :star:

**Comment by hnorthcraft** [comment]
@ljmoody @lijenn 

Can you please add story point estimates?

Thanks!
Heather



#adjudicate_memo

**Comment by ljmoody** [comment]
@hnorthcraft, I don't see how or where to add story point estimates to this pull request. Given that it spanned work over ~2 months for me and then @lijenn reviewed those, my best estimate for effort is 8pts.

**Pull request merged**
