### PR TITLE
Feature jmr #2365 cs see say edits

### PR DESCRIPTION
**Pull request by jamesmrollins**
Hi @mnallajerla .  

## Please Note

- This pull request will update all the gif files noted in #2365 QA PROD.  I have checked them off to indicate they are now up to date with latest Sim UI graphics.
- Since these are files, GitHub doesn't know that they have been updated; therefore, it will not automatically replace them when this branch is merged.  The files in the Master branch **must be deleted prior to merge.**  
- Please let me know if you need assistance.

### CODE REVIEW

**Comment by mnallajerla** [comment]
Hi @jamesmrollins -

Just to confirm I have the steps right:

- [ ] Delete all the GIFs named here 
- [ ] Approve this pull request & merge to master
- [ ] Delete branch

That sound right?

**Comment by jamesmrollins** [comment]
Hi @mnallajerla 

- The procedure you outline above is correct.
- Don't forget to approve the review (see below).  I will drop @lijenn so it will go forward.

image

**Comment by mnallajerla** [comment]
@jamesmrollins - I think @lijenn wanted to look into the deletion process and potential merge conflicts (?), so I am adding her back as a reviewer. Thank you for all your help teaching and orienting me!

**Comment by lijenn** [comment]
Hi @jamesmrollins! Just making sure I also read this right.

I believe GitHub does track when files (e.g. the GIFs files) are updated. 
So I don't think @mnallajerla needs to delete the old files on Master?

For example, here's the [version history of the s5_i_information.gif](https://github.com/lzim/teampsd/commits/master/resources/gifs/mtl_2.0/s5_i_information.gif) that GitHub tracked.

I worry that deleting the files in Master may cause a potential merge conflict.

How we've updated gifs in the past was just re-uploading the new gif, but ensuring the name of the file was the same, and then make a pull request to Master and that's all there is to it :)

Please LMK if I misread/misunderstood something @jamesmrollins

**Comment by mnallajerla** [comment]
Thank you @lijenn ! @jamesmrollins let me know this is good to merge since the deletions are not needed, so I will go ahead and merge.

**Review by mnallajerla — COMMENTED** [review]
Looks good to go after review from both myself and Jenn

**Comment by hnorthcraft** [comment]
#adjuducate_memo @lijenn 
can we update the SP, I have already added the operations label

**Pull request merged**
