### PR TITLE
Update pre_meeting_checklist.md

### PR DESCRIPTION
**Pull request by branscombj**
A simpler, more straightforward checklist would be helpful to guide the 30-minute pre-meeting prep. This is an effort to reduce the hodgepodge of bold and items that aren't related to co-facilitator pre-meeting prep. The actual checklist of steps needs further specificity.

### CODE REVIEW

**Comment by dlkibbe** [comment]
Hi @branscombj - I think the edits are very helpful. Suggestions/comments:
1. Should this be called "Pre-Session" checklist since GitHub, videos, say-see guides, etc. refers to the meetings as sessions
2. Maybe go back to original words: 
     b. Check the session_resources card at the top of each session column to review relevant 1) platforms and 2) guides/checklists to prep for each session. 
3. Re: "+ Note specific time stamps on the [team_tracker checklist or is it the say checklist?](https://mtl.how/team_tracker)"      Time stamps are in the say guide and say checklist - do we want to make notes in the say checklist and transfer them to the team tracker file?

**Comment by branscombj** [comment]
> Hi @branscombj - I think the edits are very helpful. Suggestions/comments:
> 
> 1. Should this be called "Pre-Session" checklist since GitHub, videos, say-see guides, etc. refers to the meetings as sessions

YES. I made that change. THanks!

**Comment by lzim** [comment]
This is a stale PR closing.

**Comment by hnorthcraft** [comment]
#adjuducate_memo @lijenn @lzim 

It look like this ended up going stale, should this be re-classed as closed as unplanned. Or since it looks like there was some work, can we update the SP, I have already added the operations label

**Pull request closed without merging**
