### PR TITLE
Jane 032118

### PR DESCRIPTION
**Pull request by branscombj**
I'm not entirely confident about these alternatives for Sessions 6-7. Tom and Debbie, I think it could be really helpful if we had some time to put our heads together about the LOs for the MM, PSY and AGG modeling sessions.

### CODE REVIEW

**Comment by TomRust** [comment]
I understand that we want good scores on the participant feedback, but it seems like we've moved way down the Bloom hierarchy to get them.  After running experiments with the model, participants should be able to do more than "name," "describe," and "discuss."  If they run multiple experiments to test multiple improvement hypotheses, they should all be able to say that they "analyzed," "synthesized," and "evaluated."

Will participants have enough time to run multiple experiments and compare outcomes?  

Since we're moving to a menu after session 4, how about we have 12 possible modules (3 per model) that they can choose to fill their remaining 8 sessions?  Between all the LOs we have written so far, I'm sure we could put together 12 three-LO sessions.  This will allow them to both focus on the services they think are most important, and go to the depth they want.

**Comment by TomRust** [comment]
I ran into this issue (not having enough time to run and compare experiments) when I was adding details to session script #4, too.  I don't know how we can get very much out of the simulations with so little time.  Running one simulation per model isn't enough to develop intuition around how the clinic should be managed, nor to develop a specific action plan to implement in their clinic.   

I don't want to just hope that the teams will be so excited about the simulations that they will continue to experiment with them after a session is over.  To me, it seems better that they go into depth on at least one model than skim the surface of four. 

My proposal above is a "have our cake and eat it too" sort of solution.  If it's going to be too much work, or take more time that we have, then I'm fine keeping it to 2 sessions per model.  

I think VA's IRB training has this same "complete 8 of 12" format.  There must be others in TMS that are set up similarly.  Maybe the EES people could show us some examples...if you all think this is something worth pursuing, of course.  :-)

**Comment by lzim** [comment]
My additions to Tom's thoughts:

I understand that we want good scores on the participant feedback, but it seems like we've moved way down the Bloom hierarchy to get them. After running experiments with the model, participants should be able to do more than "name," "describe," and "discuss." If they run multiple experiments to test multiple improvement hypotheses, they should all be able to say that they "analyzed," "synthesized," and "evaluated."

**- I agree with Tom on this.  There should be some more advanced "Bloom" in our LOs-**

It will be a forward-asking evaluation question, "I can analyze/synthesize/evaluate..." I hope everyone will be capable of doing that; but I'm worried about uniformly deep experiential learning by each participant in a session . This is why I feel like setting a least-common-denominator bar at being able to reflect back what insights they got or discuss the experiment and its results.

**-Agree and (somewhat) disagree. Agree: We need to develop our facilitation guide/instruction design to provide 'uniformly deep experiential learning.' Not sure this depth will be entirely captured by the LOs.  Disagree (somewhat): I don't want to support a 'least-common-denominator bar' either in terms of flexing more of Blooms levels by actually getting close to synthesizing, analyzing and evaluating, etc.  But, I do want the LOs (not the larger scripts/experimentation session, just the LOs themselves) to be the most plain, common everyday language we can possibly use while still honoring this required Bloom paradigm. We need national accreditation bodies from Psychiatry, Psychology, Nursing and Social Work (plus peers and counselors for our inclusion principles) to read them and get right away why they should approve it, why staff from these disciplines should learn this, and we want those staff to immediate grasp the goals of the training and see their work reflected in it. -**

Will participants have enough time to run multiple experiments and compare outcomes?

**-Gosh I think it's key to learning and developing new mental models to run multiple scenarios and compare them for experiential learning.  I think it would be better to figure out how to tailor to local team needs  and go farther with folks any given model/set of experiments, than to cover everything on a surface level.  I feel the frontline feedback is leading us this way and we need to work together to figure out how to do that and still satisfy EES requirements-**.

Since we're moving to a menu after session 4, how about we have 12 possible modules (3 per model) that they can choose to fill their remaining 8 sessions? Between all the LOs we have written so far, I'm sure we could put together 12 three-LO sessions. This will allow them to both focus on the services they think are most important, and go to the depth they want.

_I like this idea.

**-Lindsey likes this idea too.  Not sure if I understand the implications for EES.  Can you help me think through those dimensions Jane and Debbie?-**

**-THANKS ALL!-**

**Comment by lzim** [comment]
YES, Tom one other good point, for example all our CITI trainings also have the "these sessions are mandatory" and "these are your options to meet the remaining requirements format."

Since we're seen this formate in VA EES trainings (aka Talent Management System or TMS), maybe Elizabeth can help us think through how to format the accreditation this way.

**Comment by branscombj** [comment]
Sorry if my editing within Tom's comment was unclear! This could maybe be better transferred to BaseCamp, but that doesn't have any functional advantages in terms of conversation and we've started here, so I'll stick with GitHub.
 
Below (and in general), I use "course" for the 12-workshop series and "session" for each one. I use "manual" for the full batch of info we need to give a future facilitator; "session guide" for their instructions for a single session; and "script" for words for them to deliver. Also below, I am only speaking of the live, synchronous delivery of an MTL course.

A session is nominally 1 hr. I envision each one having an intro that includes roll call, technology check, logistics/housekeeping, follow-up on anything they were asked to do or voluntarily did between sessions, and introduction of the current session's objectives. Each session also needs an outro that summarizes what was covered, anything to do before next time, logistics/housekeeping, and possibly a preview of next time's objectives. That leaves probably 30-40 minutes per session for instruction, experimentation, and discussion. Does that sound about right, Lindsey? 

For the sessions involving experiments with the models (currently called 4-11), that seems like enough to explore one feedback loop or 1-3 interrelated variables? Or think of it as one or two insights?

For accreditation of a session to be delivered live, you need a "brochure" containing a fixed title, date, justification of need, target audience, and agenda with faculty (plus credentialing, planning committee etc). We made the decision to accredit each session individually. Elizabeth replied recently that we can't accredit the course of 12 sessions as one learning opportunity and specify a percentage less than 100 that participants must attend to get the credit; she said if it's 12 sessions they have to attend all 12. Maybe that exchange overlooked some nuance, but after it we reconfirmed that we're accrediting the sessions separately.

This doesn't mean we can't have optional modules. We would just develop brochures for each one, and then whenever a course is upcoming or in progress and specific date/session combos are known, that date would be filled in on that session brochure and submitted for accreditation. I don't know what the turnaround time will be for that, once all the sessions are basically "pre-approved" by our EES consultant so that we're sure they should pass muster (or once they've been approved once already). But it might be more than the amount of time a facilitator would have if they were choosing modules from one session to the next (2 weeks). We could find out.

As it is, my hope was that once we have the starting date of a course, we could project the dates for all 12 sessions and send those all off for EES approval, then just follow whatever protocol they have for rain-checks if dates change during the course period.

Given the general session outline described above, I think we could pretty easily create 16-18 session brochures and get them reviewed for likely approval. The agenda can be pretty generic and most of the other stuff is the same for all sessions; they'd just have to have a unique title and learning objectives. So the EES part isn't a big problem. The accreditation-on-the-fly and facilitator flexibility and capacity might be.

Again, this is only for live-synchronous. Asynchronous isn't hard if you record actual live sessions and submit them immediately after for accreditation (which you could skip if no team members missed that session). What's harder is to create a slick, durable recording (or set of 12 or more recordings) for use as make-up in every course delivery. Then you have production work plus piloting requirements. You get a nicer product -- with the down-side that it lacks team-specific content, comments, etc. It may also bring in a higher standard for 508 compliance because it's more for the general universe of VA users (not sure if that's the case for a "signed-up-for live, missed session"); and by that logic you may set up a situation where people go into the system and do the whole course asynchronously (and not in teams).

Hope some of this is helpful! Over and outta here!!

**Comment by lzim** [comment]
Thanks Jane, 

**-My comments below-** after your comments:

Below (and in general), I use "course" for the 12-workshop series and "session" for each one. I use "manual" for the full batch of info we need to give a future facilitator; "session guide" for their instructions for a single session; and "script" for words for them to deliver. Also below, I am only speaking of the live, synchronous delivery of an MTL course.

**-Sounds good, thanks for clarifying you use of terms. I'm going to abbreviate Modeling to Learn as MTL.-** 

**-Do we have any problems using "MTL course" and "MTL workshop series" interchangeably?  Can we clarify in our use of language which MTL materials language are for learners versus facilitators?  For example, I would stick with the term "MTL facilitation guide" for facilitators, which would be comprised of "MTL session scripts," and each session has a introductory 1-page "session overview," that Jane may be calling a guide (we formatted these in a standard way with trainees last year.  The goal was to outline the session and use consistent icons across the facilitation guide, UI materials, learner emails, to facilitate instruction via standardization. -** 

**-We also will need to have a MTL "session guide" or "how to guide" for learners, that walks through material. Stacey has been working to standardize these as pre/post-session HTML formatted emails, tailored to the team schedule, vision/learning goal, embedded with links, instructions and attached materials.-**

A session is nominally 1 hr. I envision each one having an intro that includes roll call, technology check, logistics/housekeeping, follow-up on anything they were asked to do or voluntarily did between sessions, and introduction of the current session's objectives. Each session also needs an outro that summarizes what was covered, anything to do before next time, logistics/housekeeping, and possibly a preview of next time's objectives. That leaves probably 30-40 minutes per session for instruction, experimentation, and discussion. Does that sound about right, Lindsey?

**-Yes.  To link to prior discussions, I think we should use the do/done format in the pre/post emails and at the beginning and end of a session. We also had an icon for the do/done format of hexagons together, which we called "putting it together." By which we meant to encourage synthesis of any given MTL component within the larger whole of activities, lessons, goals, etc.-**

**-For the 30-40 minutes per session for instruction experimentation and discussion, the anchors should be within a combination of four model/UI/facilitation elements common across sessions:
1) the team decision matrix that comprises the Expanded Output Tile and associated icons:  Question, Hypothesis, Findings, Decision. 
2) the "Experiments Tile" categories of "Team Data," "Supply," "Engagement Pattern," "New Patients and Referrals," and "Sensitivity." These are associated with... 
3) The "Reveal Complexity" feedback loop selections in the "Experiment Timeline" typically, "Balancing Patients," "Wait times and RVI or Referrals," and "Overbooking and No Shows," with two model-specific reveals: "Engagement after 3 months" (Psy) and "Effects of Overtime" (Agg). 
4) Finally, there is experimentation with "Patient Cohorts" (MM and Psy) and "Patient Services" (Agg only).-**

For the sessions involving experiments with the models (currently called 4-11), that seems like enough to explore one feedback loop or 1-3 interrelated variables? Or think of it as one or two insights?

**-Let's link this to our team tailoring/modular conversation and Karen's diagram (sent via email on Friday). Due to time constraints, we may only be able to get 1 or 2 insights out of each session. But, there is more than one way to arrive at those insights.  And, I think we need to go much farther than exploring 1 feedback loop or 1-3 interrelated variables to achieve our goals to
1) Provide the type of experimentation and experiential learning that... 
2) Changes folks schemas (aka "mental models") enough to...
3) Apply new heuristics (aka "rules of thumb) in their day-to-day decisions.-**

**-See my notes below about Modules and Accrediting each of the sessions.-**

For accreditation of a session to be delivered live, you need a "brochure" containing a fixed title, date, justification of need, target audience, and agenda with faculty (plus credentialing, planning committee etc). We made the decision to accredit each session individually. Elizabeth replied recently that we can't accredit the course of 12 sessions as one learning opportunity and specify a percentage less than 100 that participants must attend to get the credit; she said if it's 12 sessions they have to attend all 12. Maybe that exchange overlooked some nuance, but after it we reconfirmed that we're accrediting the sessions separately.

**-Yes, we have circled back to this many times. We must accredit each of 12 sessions individually.-**

**-This doesn't mean we can't have optional modules. We would just develop brochures for each one, and then whenever a course is upcoming or in progress and specific date/session combos are known, that date would be filled in on that session brochure and submitted for accreditation. I don't know what the turnaround time will be for that, once all the sessions are basically "pre-approved" by our EES consultant so that we're sure they should pass muster (or once they've been approved once already). But it might be more than the amount of time a facilitator would have if they were choosing modules from one session to the next (2 weeks). We could find out.-**

**-Let's find out the turnaround for accreditation. What I would like to propose is perhaps an adaptive design (following staff feedback, Karen's ideas - see the email, and David's point about changing the research design):

**-We propose for a rolling enrollment/facilitation model, which occurs in 6 month waves, for a 6 month course.  In our grants we propose that a "facilitation team" will manage 1 "regional health care system" at a time.-** 

**-Most likely, in the beginning, we will use a 3 person "facilitation team" comprised of 1) a Team PSD systems expert (Tom, David, Lindsey, Jane, Debbie), 2) a VA Central Office Technical Assistance Specialist, and 3) Team PSD project administration (Stacey).-** 

**-A "regional health care system," must have 3 locations (a location is a "division" or "community-based outpatient clinic") participate, each location may have 1-10 "teams" of providers (~5-30 providers). Facilitators will hold live, virtually facilitated sessions, which require 3-4 teams to meet at the same.-**

**-Modularization may be challenging to reconcile with the multiple team facilitation format we anticipate using Adobe Connect.  But, if we group the teams together, for example:  BHIP (generalist teams) together, and specialty teams (PTSD and SUD teams, for example). They tend to have similar goals, quality gaps, service focus, patient cohort focus, etc.  I welcome all of your best ideas about this for sure.-**

**-In each of our recent grants, we proposed to engage 4 regional health care systems in MTL for 6 months each (with 6 months of active instruction, and necessary pre- and post- follow-up activities).-** 

**-With this phased timeline for roll-out, we could pursue accreditation in quarterly (3 month) batches based on the schedule as it is finalized. It would be great if this could go hand in hand with modularization and adaptive tailoring to teams (see more notes after Jane's below.-**

As it is, my hope was that once we have the starting date of a course, we could project the dates for all 12 sessions and send those all off for EES approval, then just follow whatever protocol they have for rain-checks if dates change during the course period.

Given the general session outline described above, I think we could pretty easily create 16-18 session brochures and get them reviewed for likely approval. The agenda can be pretty generic and most of the other stuff is the same for all sessions; they'd just have to have a unique title and learning objectives. So the EES part isn't a big problem. The accreditation-on-the-fly and facilitator flexibility and capacity might be.

**-I think that with the exception of needing the specific dates for each "set" (possibly by quarter, see above) of accreditation brochures. I think it makes sense to stick to the longstanding plan that MTL will be a 6-month course with teams agreeing to substitute two meetings per month (2 hours/month; 12 hours total).-**

**-However, as we continue to consider these four things:
1) Frontline provider feedback about tailoring to their local team needs and goals
2) Time constraints for each session
3) The potential breadth and depth of the four model/UI/facilitation elements common across sessions I covered above, and
4) our goals to a) Provide the type of experimentation and experiential learning that, b) Changes folks schemas (aka "mental models") enough to, c) Apply new heuristics (aka "rules of thumb) in their day-to-day decisions.
**_I think we likely want to accredit perhaps 4 or so brochures per model, with the idea that a team may want to go "in-depth" with all the possible insights/learnings they can get from some of the specific models/modules/sessions that best fit their team needs:-**

Again, this is only for live-synchronous. Asynchronous isn't hard if you record actual live sessions and submit them immediately after for accreditation (which you could skip if no team members missed that session). What's harder is to create a slick, durable recording (or set of 12 or more recordings) for use as make-up in every course delivery. Then you have production work plus piloting requirements. You get a nicer product -- with the down-side that it lacks team-specific content, comments, etc. It may also bring in a higher standard for 508 compliance because it's more for the general universe of VA users (not sure if that's the case for a "signed-up-for live, missed session"); and by that logic you may set up a situation where people go into the system and do the whole course asynchronously (and not in teams).

**-I think that for asynchronous/videos the turn around time for accreditation would be key to determining our approach. If in the long run, we will not have a "facilitation team" that includes a Team PSD systems person, and we may not have funding/grant money, we need the accreditation burden for vacillations and Team PSD to be as low as possible.  In fact, other that the instructional goal of keeping the whole team moving forward together, the other goal of the videos was to reduce any accreditation hassles for the facilitator.-**

**-I think that if we ultimately had our first 3 non-modeling sessions recorded in the same standard way, some of the Teams who do the live training may even benefit from have a "clean" option available, even if not tailored to their team (they will still get the team tailored HTML emails between sessions regarding what was done and what to do ("do/done").-**

**-If we want to accredit four sessions for each model, then that would be 16 videos, plus those first 3.  So, approximately 20 total 60-minute sessions, which would be using a generic set of team data and primarily be to ensure that learners are able to find and use the resources and keep up with their team when they miss. For team specifics, they would get caught up via email or the next session.-**

 **-Like our TMS trainings and CITI trainings, the individual would chose the modules/sessions that their team did and get credit for those.-**

**-It may not be super likely, but some managers may watch the videos even if they are not in the live facilitated team meetings.  In addition, some teams may use the videos to learn from modules/sessions that extend beyond their 6-months of live, virtual facilitation. The videos could show them how to work through the other models for team insights.  It may even help them to sustain their use of the tools.-**  

**-Over time, we may even release updated module/session videos for new trainings/learnings or as "boosters" for teams that completed the training before.  We could evaluate how the video vs. live versions work too.-**

**-On the other hand (and a complete 180 from what we've been planning), teams may want to record their sessions for when someone misses, but we may not want to offer accreditation for missed sessions.  It may just be available in the team folder for a limited time, so that they can catch up, which without accreditation, may incentivize attendance.-**

**-That being said, people miss meetings, especially when they're over six months. Even our most dedicated folks have to miss from time to time.  At the same time, people like videos, even when they do attend.  It is more upfront work to have a clean copy of 20 piloted, 60-minute videos, but I think it would save a substantial amount of work over time as compared to 1) accrediting as we go, 2) accrediting based on when folks miss, and 3) once accredited we can have it as a recurring course, which requires increasingly less work over time.  We have several of these in NCPTSD.  Note to Jane:  I don't think there is any accredited course that gets us around 508.  So, a clean copy that is pilot tested is likely easier to meet this requirement.-**

**-I suspect that the upfront work to record and pilot test the 20 videos will serve perhaps an incredibly important function:  It will help us insure that is at least one version of MTL accessible that is delivered with 100% fidelity to our MTL model.  So, it may also serve several other purposes, including being a resource that we lean on as we train new facilitators.-**

Hope some of this is helpful! Over and outta here!!

**-This is all very helpful Jane, and everyone! I hope I have been helpful too.-**

**Comment by TomRust** [comment]
We've all worked on a new copy outside of GitHub, which Jane is going to upload today (4/10).  So, I'm closing this branch, as all our collective changes will be there instead of here.

**Pull request closed without merging**
