### PR TITLE
Update TeamTable

### PR DESCRIPTION
**Pull request by saveth**
Only finished updating CC, MM, and Agg Models. Still need to update Psy Model code, which the underlying data from the ModelParameters file had more substantial changes.

### CODE REVIEW

**Comment by saveth** [comment]
The TeamTable R code is now updated to read the latest update to the ModelParameter.xlsx file. Please review and merge. You can also start using it to compile the document for the teams.

**Comment by saveth** [comment]
@holbrooa @staceypark please review and integrate with master. The R script now includes the new labels/languages from the ModelParameters file as well as some of the shorthand symbols in #64. @holbrooa it'll be easier for you to view the output html file, and @staceypark can copy the necessary code chunks in the Rmd file into the appropriate Team folders.

**Comment by saveth** [comment]
@lzim  can you review and approve the pull request since both Andrew and Stacey are out? I've updated the code to reflect our discussion on Thursday. Thanks.

**Comment by holbrooa** [comment]
Done merging.

**Pull request merged**
