### PR TITLE
Feature gh pages contribute

### PR DESCRIPTION
**Pull request by jamesmrollins**
This is an update to the Team PSD manual that explains how to improve the Team PSD manual.

### CODE REVIEW

**Review by mnallajerla — APPROVED** [review]
Thank you @jamesmrollins  ! These instructions are very helpful.

**Comment by mnallajerla** [comment]
Hi @jamesmrollins - we discussed this morning at train_workflow, here are some more possible errors in this chapter. 

There are a couple sections where these images are present with no instructions (for example find and edit markdown file) and then there are a couple sections where it is redundant. Please see below for images. 

Apologies for not catching it sooner: 

image

image

**Comment by jamesmrollins** [comment]
No worries. I'll get these fixed today. These are caused by that wrong instruction I warned you about! So, school of hard knocks.

**Comment by mnallajerla** [comment]
I see, that makes sense. Thank you @jamesmrollins :)

**Pull request merged**
