### PR TITLE
Feature gh pages model update process

### PR DESCRIPTION
**Pull request by jamesmrollins**
This pull adds the automatic model update and deployment procedure.

### CODE REVIEW

**Comment by staceypark** [comment]
@jamesmrollins sorry just turning to this now. 
I notice you closed this without merging. Is there a new pull request coming instead or should we merge this?

**Comment by jamesmrollins** [comment]
Hi @staceypark .  Yeah, I have to update the process yet again.  So I closed this and will update next week . . .  James

**Comment by jamesmrollins** [comment]
Hi @staceypark .  OK, this pull request should be good to go.  I made the updates I needed to reflect how to process a model file locally and then how the actions will deposit the files where they need to go.  I also updated the diagram to reflect the new information.  

BLUF:  Vensim model processing (such as saving as a different file format like binary) MUST be done on a client.  Thus we cannot automate the conversion process in the web-based git.  However, we can accomplish many of the same ideas using a client-based GitHub desktop. When we get our new modelers on board, I will train them up.

**Comment by staceypark** [comment]
Thanks @jamesmrollins !! 💯

**Pull request merged**
