### PR TITLE
Rita see guides disclaimer 2020 02 25

### PR DESCRIPTION
**Pull request by ritahitching**
Hi Stacey, 
#1048 
Please accept the pull request for the See Guides S1 -S12 and MTL Red Part 1 and Part 2, I added a disclaimer for the self-directed learners. 
thanks, Rita

### CODE REVIEW

**Comment by ritahitching** [comment]
completed - pull request submitted.

**Comment by staceypark** [comment]
@ritahitching thanks for adding the disclaimer to the guides.
I notice that "Modeling to Learn" is spelled wrong throughout - Modeling has **one L** not two.

Please fix and let me know when you do.

**Comment by ritahitching** [comment]
@staceypark 
I've edited the word Modeling across all the session. Thanks for noticing. 
thanks,
Rita

**Comment by staceypark** [comment]
@ritahitching I'm also not sure why "facilitated" "team" and "meetings" are capitalized.
I believe our convention is to italicize *Modeling to Learn* and capitalize "Live" "Facilitate" or "Video" when we are talking about versions of MTL

**Comment by ritahitching** [comment]
@staceypark 
Thanks for clarifying the formating of the sentence. I'll update the S1-S12 to reflect:

**Disclaimer:** If you are a self-directed learner, then some of the details in the guides may not apply to you.  These guides were developed for facilitated _Modeling to Learn_ live team meetings.  

Please confirm. thanks!

**Comment by staceypark** [comment]
@ritahitching I updated your comment and it looks good now.
"live" should be capitalized since it is a version of MTL, as I stated in my previous comment.

**Pull request closed without merging**
