### PR TITLE
Dlkibbe post tests session 11 and session 12

### PR DESCRIPTION
**Pull request by dlkibbe**
@Bowlied @lzim @staceypark @branscombj 
Please see question in session 12 post-test comment.

### CODE REVIEW

**Comment by staceypark** [comment]
@Bowlied @lzim @branscombj 
in case you can't find the question - 
Session 12 post-test is challenging because it is more about team planning. 
Can we include open-ended questions on this post-test to get individual feedback on MTL?

> @Bowlied @lzim @staceypark @branscombj
> Please see question in session 12 post-test comment.

**Comment by staceypark** [comment]
@dlkibbe for questions 6 & 7 on session 11, I think they are fine to include because I expect the learners should know those. @lzim ?

**Comment by Bowlied** [comment]
Hey team,

We can add open ended questions, however the accreditation requirement for post test requires the questions to be measurable.

Multiple choice/true or false.

Thank you,

Elizabeth

**Comment by staceypark** [comment]
@Bowlied thanks! In that case, I think it would make the most sense to keep them multiple choice or true/false.

Do we need to have 10 questions for accreditation or can we have 8 and just take out the two multiple choice questions?

**Pull request merged**
