### PR TITLE
Rita see say continuity 2020 02 25

### PR DESCRIPTION
**Pull request by ritahitching**
Hi Stacey, 
#1047 
Compare SEE and SAY Guides S1 - S5 within and across sessions for continuity and consistency
Content, wording, formatting, orientation and in consideration for changes from MTL 1.8 and MTL 2.0
I added the drafted changes based on my review.
I have a spreadsheet with additional details if needed. 
thanks,
Rita

### CODE REVIEW

**Comment by staceypark** [comment]
@ritahitching i'm not sure what you mean by additional edits, or why you're tracking anything outside of GitHub? Can you explain what you mean by that?

**Comment by ritahitching** [comment]
> @ritahitching i'm not sure what you mean by additional edits, or why you're tracking anything outside of GitHub? Can you explain what you mean by that?

I

**Comment by staceypark** [comment]
@ritahitching I'm still not sure what changes you are scrubbing for in this documentation?

You've updated the content of your pull request to say "Content, wording, formatting, orientation and in consideration for changes from MTL 1.8 and MTL 2.0", which I would expect to include changes from "Team Data Table for Sim UI" being changed to "Team Data Table", but I'm still seeing that hasn't been fixed.

Consistent with the guidance we gave previously, we DO NOT want to change numbering across the SEE & SAY guides. I noticed you changed a bunch of the bullets to letters, but we DO NOT want to do this. (You can read further about the specific decisions here: #577). 

It also looks like most of the changes you made were to add bold formatting in places, add quotations, and change line spacing. Especially with the quotations, we do not want to add any extra style changes that will create new work to be propagated throughout.

In general, we DO NOT want to be making any changes at this point, unless it will be 1) incorrect or 2) confusing for the learner.

**Comment by ritahitching** [comment]
@staceypark 
Thanks for clarifying and link to #577.

In terms of changes  MTL 1.8 and MTL 2.0 and "Team Data Table for Sim UI" being changed to "Team Data Table", that is being made in #1029 - I haven't made a pull request yet.

In my opinion, some of the instructions were **confusing** and in instances, **incorrect** particularly for the self-directed learners (MTL for All), my reasoning for the changes was as follows:

**S1**
- Section 5 I updated the sentence format to match the S1 SAY guide. I added spaces to match the S1 SEE and SAY guides. I reformated the font size of  Do section of S1 SAY guide to match the prior section in S1 SEEand replaced bullets with numbered letters to match S1 SAY.
- Matched the words that were bolded in both guides. 


**S2**
- Added a table format to Section 2 of See to match S2 in the SAY guide.  I replaced bullets with numbered letters in S2 to match the SAY guide.
- Matched the words that were bolded in both guides.


**S3**
- There is no mention in the See guide of "Navigate to the data UI at mtl.how/data" which is in the SAY guide I added it for continuity. 
- I replaced bullets with numbered letters to match the S3 from the SAY guide.


**S4** 
- There were no instructions on how to get to MTL Menu (hyperlink is there).   
- I added a sentence explaining mtl.how/menu for the printed See guide - using language from Session 3 See guide. 
- I replaced bullets with numbered letters to match the S4 from the SAY guide.


**S5**  
- No explanation as to why we change to Google Chrome for mtl.how/sim having previously said that we should only use Internet Explorer.  
- In the SAY guide, it recommends to open 2 browsers Internet Explorer & Google Chrome. I replaced bullets with numbered letters to match the S5 from the SAY guide.

**Quotations** I made changes to make the SEE and SAY match in style.  Quotations are used in some parts of both guides with no particular pattern. I was trying to make it look consistent.

**Pull request closed without merging**
