### PR TITLE
Update learning_objectives.rmd

### PR DESCRIPTION
**Pull request by branscombj**
Debbie and I worked on LOs for Sessions 1-5. If there's agreement on our assumptions and approach, we can work on the rest in a similar vein. 
Our assumption is that the "official" LOs do not have to cover everything we will teach or want folks to learn; they need to serve 3 primary purposes: 
1. Be acceptable to EES for accreditation
2. Be able to yield reasonable evaluation results when the Learning system asks participants to rate their agreement with "Having participated in the session I am able to...(LO)"
3. Be appealing to potential participants, as they are part of how the learning opportunity is presented to them

We tried therefore to
1. Meet the minimum requirement (3 per session)
2. Not go over 3 without good reason, in order to keep expectations manageable for the length of sessions
3. Avoid jargon and advanced vocabulary
4. Avoid compound objectives
5. Repeat language from the user interface to reinforce learning, e.g. in describing the lessons of each main loop

We look forward to your thoughts on the above, as well as the LO edits proposed!

### CODE REVIEW

**Comment by DrKarenWall** [comment]
In Session 1- Our Vision, I suggest adding a first LO of "Define "Modeling to Learn" and list it's components". For me, and from a nursing perspective, when I teach classes, the first thing we do is literally define the title/words and identify the literal components of that model so that we have a baseline knowledge of what we will see in the following sessions.

**Comment by staceypark** [comment]
Is it possible/allowable for someone to do the entire session asynchronously?  Like how we do trainings in the VA TMS system?  And if so, what further implications does that have for our learning objectives?

**Comment by branscombj** [comment]
That’s another question that’s been percolating in the back of my mind, Stacey! On the one hand, my assumption is that it will be in the TMS, findable and available to anybody – all 12 sessions. (It would be good to at least have some language that it’s designed to be sequential – at least through the first 4-5 sessions – and that it’s designed to be engaged in at the team level.)
However – people will have to have an administrator (you) give them access (login credentials) to the MTL-UI; and not just anyone is going to have a dataset.
This is where some models create versions that are calibrated to average kinds of numbers so that users can play with them and gain the general insights, knowing that particulars will be different in their specific context.
We’ve had conversations with Lara in which she made the points that because this is for a specific audience it might not have to meet all the most stringent 508 standards; she also talked about the fact that things produced by VA are at least theoretically supposed to be available to anyone to look at as a reason that most things do have to conform to 508.
My ramble…

**Comment by branscombj** [comment]
ok if I get this, all I just did is merge these changes to the copy on my 032118 branch!
btw, the note above is what happens when you respond to what you think is an email but is actually a ping from GitHub!

**Pull request merged**
