### PR TITLE
Sp facilitation guide edits

### PR DESCRIPTION
**Pull request by staceypark**
I took a stab at updating the scripts for Session 1-3 to better match the templates for Sessions 1-8

### CODE REVIEW

**Comment by staceypark** [comment]
I'm also wondering, do we need a Do/Done list review at both the beginning and end of the facilitation, or should the Done list come at the beginning and the Do list come at the end?  It almost seems redundant to me.

**Comment by branscombj** [comment]
RE the Do/Done list, I think it depends on what the team is thinking will be helpful. The idea for it at both ends is that Done at the top and Do at the end would be about activities between the sessions, while Do at the top and Done at the end would be previewing and recapping the current session ("tell em what you're going to tell em; tell em; tell em what you told em").

**Comment by branscombj** [comment]
I'm going for it although I'm not totally confident - but knowing the master can always be further revised!

**Comment by staceypark** [comment]
Re Do/Done: Okay that makes sense, and is something to keep in mind as we move forward with developing the guides.

**Pull request merged**
