### PR TITLE
oct_epic: Update mtl_session01_say.md

### PR DESCRIPTION
**Pull request by branscombj**
These proposed changes are to address observed needs encountered in prepping and delivering Blue 01 by Jane, Matt, Marcia, Claire, and Debbie:
1. Participants who were not part of co-planning meetings (most of the team members present) wanted more orientation to MTL. The "putting it together" info and diagram at the end of S01 does a good job of that; we propose moving it to earlier in the meeting.
2. Participants asked, who's to say whether we'll be permitted to make these "decisions" we test and learn about? Added two points about that.
3. S01 guide needs to explicitly include learner introductions. We felt it made best sense to do that at the time that we ask for their personal vision input. This ensures that we hear from everyone.
4. Given added length due to the above, we propose truncating the "Prior Team Learning Prompt" to more didactic - with facilitators' discretion to ask for a few popcorn responses.
5. It seems worthwhile to confirm who will be "team lead" during the session when everyone is already together. This reduces the necessity for ad hoc communications and tracking, and the risk of delays in being able to schedule time with them to select data.

IF THESE CHANGES ARE ADOPTED, THEY WILL NECESSITATE CHANGES TO AT LEAST THE FOLLOWING:
* Blue S01 Say Checklist
* Blue S01 See Guide
* Blue post-S01 email

### CODE REVIEW

**Comment by hmarcia** [comment]
Thank you, Jane. This looks perfect to me. :)

**Comment by dlkibbe** [comment]
Due to team members not having information about *MTL* prior to session 1, @hmarcia @clairecollie @dlkibbe discussed introducing the following concepts at the beginning of Session 1 
Modeling to Learn will:
a.	MTL will make your VA data team’s hyperlocal data transparent to you and the model will use your data for simulation, allowing you to test changes your team would like to consider without having to implement them in your real world Clinic.
b.	Potentially help realize ongoing improvements in team quality of care and team quality of work life – it is not about us telling you what to do – it is your team’s decision based on your shared vision, your priorities/needs, and your current reality – what is in your control.
c.	Support the team in developing systems thinking skills that help you to see how different factors and processes in your Clinic fit together and understand causes that are hard to see without data and modeling resources.

@branscombj

**Comment by branscombj** [comment]
@dlkibbe Please see if the edits I made, which Marcia 👍, accomplish what you are recommending. You can edit further as needed but let's see if we can get this OK'd by @lzim in time for your pre-session prep tomorrow with Marcia standing in for Claire.

**Comment by dlkibbe** [comment]
@branscombj I like the simplified MTL overview language to start session 1 but the word or words "decisions" or "team decisions" is missing from the text - this has been a key concept in our language.

**Comment by branscombj** [comment]
@dlkibbe I made further edits to try to incorporate all of the above.

**Comment by dlkibbe** [comment]
Thanks Jane - my only feedback is that I had to look up the term 'in silico' so I was sure of its meaning... "a modern word usually used to mean experimentation performed by computer" -- others may know this phrase as common.

**Comment by jamesmrollins** [comment]
@lijenn will review and will discuss with Facilitate WG 4/20.

**Comment by staceypark** [comment]
Decision: Review at 10/5 facilitate meeting

**Comment by lzim** [comment]
@mnallajerla and @lijenn 
have worked on the DEV and TEST versions of the _MTL 3.0 SEE/SAY guides_
we have implemented co-facilitators leading co-planning 2.

**Pull request closed without merging**
