### PR TITLE
Standardized version of PSY

### PR DESCRIPTION
**Pull request by TomRust**
* Variable names and units updated (even the variables that are only in Vensim)
* Model start time set to -1000 (was only -500 in previous version) -- this should improve stability in equilibrium.  This should not affect the UI at all.
* One question:  I saw two different labels describing the same sub-cohort: "Initiators who Continue," vs "Initiators who Return."  I changed them all to "Initiators who Return."  That label lines up with "Starters who Return," and is less likely to be confused with the initiators who continue in their first three months (ie, the Completers).

### CODE REVIEW

**Comment by lzim** [comment]
@TomRust Sounds good!

We/I tried to current everything to "...who Return" in @saveth's data tables and in @holbrooa's data UI too.

Thanks!

Lindsey

@jamesmrollins @branscombj @dlkibbe @staceypark @dlounsbu

**Comment by TomRust** [comment]
Great!  Then this version should be good to go!

**Comment by lzim** [comment]
Great @TomRust Should I merge it with Master, then?

**Comment by staceypark** [comment]
@holbrooa Savet wanted me to alert you that based on the changes above there, the ModelParameters.xlsx needs to be updated

**Pull request merged**
