### PR TITLE
tt3_report

### PR DESCRIPTION
**Pull request by staceypark**
Hi Savet,

I just added the tt1 code to the top of this and combined the libraries needed for both.
The issue that needs to be resolved is that the code line for going through the export files (bc, exp1, exp2, exp3) calls for all files with the .xlsx extension. 

However, that also pulls in the ModelParams file then (has same .xlsx extension), so at that point in the code it needs to ignore that.

tt3 actually consists of the reports tt1-tt3 

Thanks,
Stacey

### CODE REVIEW

**Comment by saveth** [comment]
@staceypark you'll need to edit the code where tt2/tt3 starts. Underneath 
files <- list.files()
files <- files[grepl("\\.xls",files)]

You'll need to include this line of code to remove the ModelParameter from acceptable list of files to run the rest of the code:

files <-  files[-grep("ModelParameters.xlsx", files)]

**Comment by saveth** [comment]
@staceypark I noticed that you've copied everything from the tt1 report into the teamtable_tt2_tt3_agg.Rmd file. Do you mean to only report tt1 info with tt2 and tt3 for agg? Or do you intend to report every model in a single file?

**Comment by staceypark** [comment]
You're right @saveth, it would be for all the modules. Thanks!

**Comment by staceypark** [comment]
closing this pull request. new one has been created.

**Pull request closed without merging**
