### PR TITLE
Rita 2020 03 16 issue 1120

### PR DESCRIPTION
**Pull request by ritahitching**
@staceypark please accept this updated pull request for issue #1120 
1. S1 - S12 for MTL Blue replace all 24 emails header logo
2. Add MTL Blue to pre email files
3.Add MTL Blue to post email files
4. Header logo to go to the respective SEE session.
thanks, Rita

### CODE REVIEW

**Comment by staceypark** [comment]
@ritahitching 
1. I noticed this was missing an **Epic** so I assigned it to the teams_data epic. I also noticed this was labelled with "co-i_manuscript" as well as "facilitate". This has nothing to do with the manuscripts so I removed that. (Please follow our review and training that we went through last Friday about pull requests. Include all "9 clicks" and make sure they are accurate so we have good data!)

2. All of these images are linked to the guides at mtl.how/teampsd instead of **mtl.how** where we point our learners. As you know and we have repeatedly discussed as a team in regards to resources, we **always** point our learners to mtl.how not the "works in progress" TeamPSD repository. 

I am closing this pull request, unmerged. Please fix and send me another pull request when you're done, with all "9 clicks" clicked through.

**Comment by ritahitching** [comment]
@staceypark thank you. I'll update the link and resubmit. I'm confirming the link to S1 as an example.
https://github.com/lzim/mtl/blob/master/blue/session01/s01_learner/mtl_session01_see.md
thanks,

**Comment by staceypark** [comment]
Yes this is correct. 

> @staceypark thank you. I'll update the link and resubmit. I'm confirming the link to S1 as an example.
> https://github.com/lzim/mtl/blob/master/blue/session01/s01_learner/mtl_session01_see.md
> thanks,

**Comment by hnorthcraft** [comment]
#adjudicate_memo update vs

**Pull request closed without merging**
