### PR TITLE
splash page guide

### PR DESCRIPTION
**Pull request by anthonycpichardo**
Splash page set up and guide.
Document should detail:
- [ ] How to update splash page data
- [ ] How to update site settings
- [ ]  How to resolve file size

### CODE REVIEW

**Comment by lzim** [comment]
@anthonycpichardo Discussed at #hqhuddle on 4/29/2020 

@ritahitching Has been assigned to review this pull request for #626 - I changed the assignment above. Rita did not have questions during the huddle (yet), but does have enough information in your list above to complete a thorough review.

**Goal of #626:** A new Team PSD member could review the #626 "team how to" document and know exactly what to do.
**Goal of #1384:** A checklist for a reviewer that would provide a comprehensive review.

Next Steps:
1. @ritahitching is awaiting an update from @anthonycpichardo   that clarifies exactly what she should be checking in #626  
2. In the interim, @ritahitching will review #626 to get her bearings.

**Comment by lzim** [comment]
@anthonycpichardo confirmed via Teams chat on 4/29/20 that he will update the top card to provide a review checklist.

Cross-ref note: @ritahitching @branscombj @dlkibbe - This #626 is another great example of something that needs the #1364 **Standard Header** rules defined for all the comments in the **Team PSD Manual.**

- As we discussed at **All Hands** Tuesday, we have open 23 **documents_teams** cards in the **document_tracker** and we have a draft TOC of documents like this already created on #1192 **Team PSD Manual.**

- Unfortunately, all the documents use formatting in their own ways.
- It makes it hard to use them like a manual.
- Before we create 23 more items that also use formatting in their own ways..._let’s standardize to avoid rework_ 😅 !

**Comment by ritahitching** [comment]
@lzim please confirm I can move this issue to the May milestone &  Epic?
thanks

**Comment by lzim** [comment]
@anthonycpichardo 

We may want to review this on the **va/operations** repo, since it's a splashpage guide.

@staceypark  We will need another reviewer. Can you help decide who would be best?

**Comment by anthonycpichardo** [comment]
Agreed

**Pull request closed without merging**
