### PR TITLE
Lindsey's CC Review on "c_code_test"

### PR DESCRIPTION
**Pull request by lzim**
Hi Standardization Committee (@TomRust, @jamesmrollins, @branscombj, @dlkibbe, @saveth, @staceypark),

To meet today's CC model standardization deadline, I reviewed the 745 lines of CC code on my branch "c_code_test" in the file named "Update cc_v34_2018_06_19_lzedits_2018_07_30f.mdl" I reviewed in 12 batches of commits and made 24 commit comments to highlight areas for standardization as we push to the MM Wed COB standardization deadline.

I updated the entire model to use the standard abbreviations for units. Please take a look. 
I did not change any variable names.

I believe the only remaining task for CC is to find edit all the team data (data UI/ModelParameters) definitions. I can try to tart on those, but I wanted @TomRust to see how editing in GitHub was going ASAP, rather than hold us up because I haven't gotten to that yet. 

Note: I believe anyone can search for "GET DIRECT CONSTANTS" and upload the standard definitions from the workshopped file here: https://github.com/lzim/teampsd/tree/master/quant_workgroup/ModelParameters.xlsx

James posted the Master Crosswalk prototype, so we want to bring this CC model and the CC tab of that crosswalk into alignment ASAP, so we can transition to MM.

Thanks All, please let the group know if you have any questions.

Lindsey

### CODE REVIEW

**Comment by lzim** [comment]
Thanks @dlkibbe I will work to add the standard definitions to CC tonight, and then we'll move to Agg next. If you are able start on adding the standard "ModelParameters" information to Agg (first, then move on to Psy and MM) in the AM before I do. Please go ahead. Definitely create your own branch from the Master here: https://github.com/lzim/teampsd/tree/master/model_workgroup/models
So that it can be reviewed before the edits are pulled back in to a new Master .mdl file.

We'll have @TomRust review the commends and the code in this order, so that @jamesmrollins  can get going on MTL 1.6 (Standardization) on a rolling basis, so we have it for our MTL Facilitate Pilot.
I expect that we will focus on Agg during the MTL Facilitate Pilot training, because our TeamPSD facilitators will be most familiar with it based on the team meetings they've facilitated (make sense @dlounsbu, @branscombj?.).

*CHANGE to the ORDER OF STANDARDIZATION
-CC 
-Agg Review for COB 8/1/2018
-Psy Review for COB 8/3/2018
-MM Review for COB 8/6/2018

@TomRust Our goal for your pass is to make the change to the .mdl files on GitHub, so a second set of eyes can quickly comb through them. We want to make sure that any recommended standard variable names from the sim UI development/review process and the data UI standardization/review process get captured in the Vensim models themselves. And, that there are no legacy variable names or explanations in Vensim that are inconsistent with our new standards, even if they **only** appear in Vensim and not other places.

Thanks All!

lindsey

**Comment by TomRust** [comment]
@lzim -- What is the right i text for "Appropriate Supply (75th percentile)"?

I found two versions:
An estimate of the weekly number of care coordination appointments available with this team. The estimate is calculated using the volume of care coordination visits completed with the team over one year. (appt/wk)

and

An estimate of the weekly number of care coordination appointments available with this team. The estimate is calculated using the volume of care coordination visits completed with the team over the last two years. (appt/wk)

**Comment by lzim** [comment]
I know @holbrooa double-checked this to confirm which is correct one or two years. Andrew can you confirm with Tom now?

Tom, can you say where this has fallen out of sync? e.g., .mdl files, or crosswalk or ModelParameters.xslx?

I want to make sure other things haven’t gone out of sync again!

Thanks!

Lindsey

**Comment by TomRust** [comment]
@lzim @holbrooa -- the master crosswalk says "two year," and the c_code_test says "one year."

**Comment by TomRust** [comment]
@lzim @dlkibbe @branscombj @dlounsbu @jamesmrollins  -- in the master crosswalk, we have two variables with the same name:

Row 7 & row 39 are both "True  Missed Appointment %".  

Which one should we change, the data variable, or the user-controlled variable?

**Comment by lzim** [comment]
Thanks, Andrew will weigh-in, but also try triangulating with the ModelParameters.xlsx file posted in the quant_workgroup folder of TeamPSD.

James (master) and Lindsey (c_code) both integrated our edits from the data standardization committee decisions reflected in @hokbrooa’s ModelParameters.xlsx file

I copied mine directly out of it (I thought), but either of us could have made a mistake. 

Thanks Tom!

**Comment by TomRust** [comment]
@lzim @dlkibbe @branscombj @dlounsbu @jamesmrollins -- Sorry I wasn't involved with this last week.  I should probably know the answer here...but, it looks like we're inconsistent with our plurals (eg, pts vs pt).  Usually stocks are plural, and for rates, the numerator is a plural and the denominator isn't.  It's no big deal for Vensim to have both plural and singular units.  
I'm mainly asking because it seems strange to have the stock of appointments labeled in the singular (appt), when the stock of patients is labeled in the plural (pts).

My proposal is that all stocks have plural units, and all rates have a plural numerator and a singular denominator (eg, miles per hour).  

What do you all think?

Again, sorry if this is rehashing a decision you all already made!
--TOM

**Comment by TomRust** [comment]
Thanks, @lzim, going to the "modelparameters.xlsx" clarified -- it's one year.

**Comment by jamesmrollins** [comment]
@lzim @TomRust The Master Crosswalk is consistent with the Model Parameters file.  What is the decision on the singular/plural issue with stocks and flows?

**Comment by lzim** [comment]
@jamesmrollins @TomRust Following up on the thread above. 

James, do you know how the Master got out-of-sync with the most recent version of the ModelParameters.xlsx file that Andrew posted here: https://github.com/lzim/teampsd/tree/master/quant_workgroup?

I'm not asking to put anyone on the spot, but to track down what we need to do to stop any diverging threads. Andrew posted it 8 days ago??

Thanks!  See also the latest on the Standardization Committee Issue here:
https://github.com/lzim/teampsd/issues/64

Lindsey

**Comment by jamesmrollins** [comment]
@lzim 
Well, a hypothesis maybe.  I updated the "i" information from Andrew's file right after our workshop discussion.  It may have been changed between when Andrew ended our discussion and posted it on Github.  Since I didn't go back to Github to check, I may be out of date and will have to double check before the next crosswalk upload.

James

**Pull request closed without merging**
