### PR TITLE
Update mtl_session06_see.md

### PR DESCRIPTION
**Pull request by branscombj**
replacing with contents from mtl.how

### CODE REVIEW

**Comment by staceypark** [comment]
@jamesmrollins could we add a gif in this session showing learners how to navigate to the chat box and enter text in?

**Comment by staceypark** [comment]
@dlkibbe I noticed you took out the Model Diagram in the "i" information review in the pre-session "Done". Are we changing this or did this not make sense? If we are making a change on this, we need to also change the post-session 5 "Do"

**Comment by dlkibbe** [comment]
@staceypark error on my part I realized after I made the pull request that it was a between session "Do" - during the session 5 we only examine the "i" information in the Experiments tile. Reject that change.

**Comment by staceypark** [comment]
manually merged.

**Pull request closed without merging**
