### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by joycepyang**

### CODE REVIEW

**Comment by LZIM** [comment]
I am thinking these pull requests are old and you created a new branch when you uploaded as these "patch-3" names are defaults supplied by Github.  So, I'll close this for now.  Thanks!

**Comment by joycepyang** [comment]
Hi Lindsey,
Sorry for all these notifications as I try to figure out how to just push to the facilitation guide, rather than send to different branches. 

I wish there was a way to experiment without flooding your inbox!

I will try again with the "upload" function that has worked for others rather than "create new file" that I was trying, tomorrow.

Thanks,
Joyce

**Comment by lzim** [comment]
Hey!  

There IS a way to push just push to the facilitation guide rather than create a new branch : )

Remember we found that out together.  You choose the facilitation guide branch at the bottom (or whatever other Team PSD repository branch is relevant). For this, you chose to create a new branch, which you have an option to name, (but defaults to "profilename-patch"). 

More to the point,I want uploads to facilitation guide to ping me.  I do not have time to look for them, so I'd rather have them just be in my "feed" per the Basecamp conversation.  Then, I know who and what I need to respond to next. I need the technology to help with this, I cannot get it all in my working memory with all task-switching and learning I do each day.

Finding things like this help me know what's needed, not pinging me, does not tell me where folks are encountering barriers and not making progress.  If I see what people are doing, then I can be responsive.

I've synced the Team PSD repository and the Team PSD GitHub account so that progress on GitHub is tracked as progress in Basecamp too.

Thanks Joyce!

Lindsey

**Comment by lzim** [comment]
Also, should we close these patch branches?

**Pull request closed without merging**
