### PR TITLE
Replace "tile" with "section"

### PR DESCRIPTION
**Pull request by branscombj**

### CODE REVIEW

**Comment by jessfroe** [comment]
@branscombj @staceypark and I did replace tile w section for S05, so we just need to make sure all other guides incorporate this change as well

**Comment by branscombj** [comment]
I'm confused. I thought the versions y'all just brought into https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/learner_see were the latest; but the Session 5 there still had "tile" in it. Hnh?

**Comment by staceypark** [comment]
@branscombj the changes I merged are from mtl.how
the ones @jessfroe is referring to are the open pull requests.
Let me go ahead and merge them so you and @dlkibbe can start from there.

**Comment by branscombj** [comment]
OHHHHH! Thank you!

**Comment by staceypark** [comment]
@branscombj @dlkibbe 
ok my changes to the Session 5 SAY guide and @jessfroe changes to Session 5 SEE guide have been merged!

**Pull request closed without merging**
