### PR TITLE
Addition of "what is/data ui vs. what if/sim ui" graphic

### PR DESCRIPTION
**Pull request by staceypark**
I added the "what is vs. what if"graphic to S1-S7 facilitator guides.
Can you all take a quick look and confirm that the placement makes sense? Or needs to be moved? Or we need extra text surrounding it?

Once this pull request is resolved, I'll replicate our decisions into the Learner SEE guide on mtl.how

### CODE REVIEW

**Comment by branscombj** [comment]
I think it looks fine. Seems it's at the end of some and beginning of others, but I'm good with those choices.

**Comment by dlkibbe** [comment]
@staceypark @lzim @branscombj The placement for sessions 2-7 make sense to me. Question that pops up in my brain is "should this graphic be included in session 1 when we haven't even mentioned the Data UI or the Sim UI yet?" Just wondering if it cause more questions (i.e. take time to explain) when the team vision development is the focus.

**Comment by lzim** [comment]
Yes! @dlkibbe @branscombj and @staceypark

This needs to be in s1! Definitely.
Not just s2-s7.

Also, I about why not the SEE file, which is where they are most urgently needed.

@staceypark, will you please add those?
:smile:

**Comment by staceypark** [comment]
Ok merging these in and adding them to the see files in the same places as well!
Thanks :)

**Pull request merged**
