### PR TITLE
Kibbed see

### PR DESCRIPTION
**Pull request by branscombj**
Pulling in some edits DK did yesterday.

### CODE REVIEW

**Comment by lzim** [comment]
@branscombj

See my comments about the edits from @dlkibbe you pulled in to your kibbe_see branch

**Comment by branscombj** [comment]
> @branscombj and @dlkibbe
> 
> I prefer the level 3 (###) headers for the respective goals/emphases of the intersession checklist.
> 
> And I do not like the #Additional Resources Header as that is not at all what follows.
> 
> * What follows are the main substantive goals and emphases to prioritize and practice when tailoring to your team during the intersession meeting, while maintaining fidelity to the MTL theory of change.

When Tom and Debbie and I spoke yesterday, we collectively felt that there needed to be a separation between the "checklist" - do these steps in your between-sessions meeting - and the other important information they should bring in. I worry that facilitators will feel overwhelmed by the extensive content and not see it as a manageable guide to what they need to get done during the inter-session prep meeting. Since the information we tentatively labelled as "Additional Resources" is not all applicable to every session, it won't all be applied in each meeting, so we saw it as reference material.

An alternative that Debbie suggested was to have one inter-session checklist for each quarter of the 12-session plan. Then only relevant info would be included. Would that be better?

**Comment by lzim** [comment]
@branscombj and @dlkibbe 

Add @tomrust, since you mentioned "Tom" but didn't "mention" @TomRust 

- NOTE: I'm VERY concerned that the intersession checklist was edited two hours ago without a pull request approved by me, and a meeting with the TAS in less than one hour.**

-  Heading-wise and order-wise the substantive **goals** and **emphases** to **prioritize** and **practice** when **tailoring to your team** during the intersession meeting, while maintaining **fidelity to the MTL theory of change.**

- It needs to be that way in formatting as well, for precisely the reasons you state.

**- Let's talk. My eyes glaze over when I see this:

eyes_glaze_over


> When Tom and Debbie and I spoke yesterday, we collectively felt that there needed to be a separation between the "checklist" - do these steps in your between-sessions meeting - and the other important information they should bring in. I worry that facilitators will feel overwhelmed by the extensive content and not see it as a manageable guide to what they need to get done during the inter-session prep meeting. Since the information we tentatively labelled as "Additional Resources" is not all applicable to every session, it won't all be applied in each meeting, so we saw it as reference material.
> 
> An alternative that Debbie suggested was to have one inter-session checklist for each quarter of the 12-session plan. Then only relevant info would be included. Would that be better?

**Comment by branscombj** [comment]
Who can get on a call asap? I'm available. 
@dlkibbe @lzim  @TomRust @dlounsbu 
Lindsey, I do wonder if we share that we have *content* for the inter-session checklist and want to co-create with them the *format* that works best for all our first wave of facilitators.

**Comment by lzim** [comment]
@dlounsbu and I are on Lucid NOW

**Comment by lzim** [comment]
The problem with the edits you made yesterday are that it is focused on content and format without emphasizing the _MTL_theory of change - the why and how of what to prioritize and practice tailoring to the team, while maintaining fidelity.

- Meaning it focuses on the details, not the overarching causal theory of change.

**Comment by dlkibbe** [comment]
@lzim the issue is time - it is rare that we have made it through an agenda for a team session with sufficient time for interaction and questions which enhances future engagement and participation. By adding or shifting to the theoretical vs. the application of the skills that leaves even less time for interaction and questions. What is your strategy for how we can do both while engaging the learner?

**Comment by lzim** [comment]
@dlkibbe @branscombj @TomRust @dlounsbu 

Application without consistency with the _MTL_ theory of change can never occur.

**Comment by lzim** [comment]
@dlkibbe @branscombj @dlounsbu @TomRust @staceypark 

This is a great question, Debbie! 👍 

Consistent with 

1. our funded research proposals,
2. guiding vision and theory of change (participatory learning to develop systems thinking), and
3. all research on fidelity, 

the answer to the strategy for "how" to make sure an intervention is delivered as intended (i.e., to make sure it works, consistent with it's evidence base), is to "prioritize" and "practice" with supervision and fidelity ratings to establish competence.

We will work very hard to do this at the F2F!

**Pull request closed without merging**
