### PR TITLE
+ file upload instruction, - module-specific info

### PR DESCRIPTION
**Pull request by branscombj**
Seemed like there needed to be  a step after 3 that says to copy the filename and a step between 5 & 6 to finish describing how to load the data file. I tried to do as little to change the numbering as possible. If accepted we do have to make the Say file numbers line up.
Could we make the gif about going into the data ui go all the way to pointing to the folder and file?

### CODE REVIEW

**Comment by dlkibbe** [comment]
The step that @branscombj notes above in her comment was included in the say file.  
I'm not a fan of the "Orient Yourself to the..." language but it makes more sense in the see file. 
It seems just as easy to say "Review the MTL Home Page" and "Review the Sim UI Main Page"
Note @staceypark and @jessfroe - not sure why we say "landing page" in see and say when the title at the top says "Home"

**Comment by branscombj** [comment]
> I'm not a fan of the "Orient Yourself to the..." language but it makes more sense in the see file.
> It seems just as easy to say "Review the MTL Home Page" and "Review the Sim UI Main Page"

I changed the language to more friendly words. See what you think, @dlkibbe

**Comment by lzim** [comment]
I agree w/you @branscombj re: “review” is simpler

**Comment by staceypark** [comment]
I have it open right now, I think @branscombj changed to "check out". Should we do "review" @lzim ?
Also, I agree with @dlkibbe on "Home" page instead of "landing"

**Comment by staceypark** [comment]
@branscombj @dlkibbe @lzim 
I see that changes you made introduce the Team Data Menu Maintenance right after they "explore the landing/home" page instead of when they go through the steps to Start a New Session.

I don't think we should change the order for this as this goes against the order that we introduce it in the videos. Or, we can add another pop-up on the video.

Thoughts?

**Pull request merged**
